services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking_api
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=booking_api_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
    command: sh -c "php-fpm"  # Запуск php-fpm

  db:
    image: mysql:5.7
    container_name: booking_api_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: booking_api_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx_booking_api
    ports:
      - "8082:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_booking_api
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
